//! Chat message types and the vendored 2507-Instruct ChatML renderer.
//!
//! The Qwen3-30B-A3B-Instruct-2507 chat template (pinned revision
//! `0d7cf23991f47feeb3a57ecb4c9cee8ea4a17bfe`) is replicated here directly
//! in Rust; no Jinja engine runs at inference time. For the supported roles
//! the template reduces to plain ChatML:
//!
//! ```text
//! <|im_start|>{role}\n{content}<|im_end|>\n     per message
//! <|im_start|>assistant\n                        when generation is requested
//! ```
//!
//! with one structural quirk kept for fidelity: a *leading* system message
//! is emitted by a preamble block and skipped by the message loop, while a
//! system message later in the conversation is rendered in place like any
//! other turn. Both paths produce the same ChatML shape, so the observable
//! output is identical to the naive per-message rendering — the fixture
//! snapshots in `fixtures/chat_fixtures.json` (generated by the reference
//! `transformers` implementation) prove it.
//!
//! Out of scope for v0, by design: the `tools` system-block branch,
//! assistant `tool_calls`, and the `tool` role. Those inputs are rejected at
//! parse time ([`Role`] has no variants for them) rather than rendered
//! wrong. Non-string message content (the template coerces it to `""`)
//! cannot be expressed here either: [`ChatMessage::content`] is always a
//! string.

use std::fmt;
use std::str::FromStr;

use serde::{Deserialize, Serialize};

use super::TokenizerError;

/// Chat roles this build renders.
///
/// Serialized in lowercase (`system` / `user` / `assistant`), exactly as
/// they appear inside `<|im_start|>{role}`. Deserializing any other role
/// string fails; see [`TokenizerError::UnsupportedRole`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    /// Instructions to the model, normally the first message.
    System,
    /// A human turn.
    User,
    /// A model turn.
    Assistant,
}

impl Role {
    /// The lowercase role string used inside ChatML markers.
    pub fn as_str(self) -> &'static str {
        match self {
            Role::System => "system",
            Role::User => "user",
            Role::Assistant => "assistant",
        }
    }
}

impl fmt::Display for Role {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl FromStr for Role {
    type Err = TokenizerError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "system" => Ok(Role::System),
            "user" => Ok(Role::User),
            "assistant" => Ok(Role::Assistant),
            other => Err(TokenizerError::UnsupportedRole(other.to_owned())),
        }
    }
}

/// One chat turn: a role and its text content.
///
/// `deny_unknown_fields` makes unsupported inputs (e.g. `tool_calls`) a
/// parse error instead of silently dropping template-relevant data.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ChatMessage {
    /// Who is speaking.
    pub role: Role,
    /// The message text, inserted into the template verbatim.
    pub content: String,
}

impl ChatMessage {
    /// A message with the given role and content.
    pub fn new(role: Role, content: impl Into<String>) -> Self {
        ChatMessage {
            role,
            content: content.into(),
        }
    }

    /// A `system` message.
    pub fn system(content: impl Into<String>) -> Self {
        Self::new(Role::System, content)
    }

    /// A `user` message.
    pub fn user(content: impl Into<String>) -> Self {
        Self::new(Role::User, content)
    }

    /// An `assistant` message.
    pub fn assistant(content: impl Into<String>) -> Self {
        Self::new(Role::Assistant, content)
    }
}

/// ChatML turn opener, `<|im_start|>`. A single added token (id 151644) in
/// the pinned vocabulary.
pub(crate) const IM_START: &str = "<|im_start|>";

/// ChatML turn closer, `<|im_end|>`. A single added token (id 151645); also
/// the primary stop token.
pub(crate) const IM_END: &str = "<|im_end|>";

/// Render a conversation exactly as the pinned 2507-Instruct template does
/// (tool-free path).
///
/// Mirrors the template's structure: the preamble emits a *leading* system
/// message; the loop emits user turns, non-leading system turns, and
/// assistant turns (all the same ChatML shape once `tool_calls` is out of
/// scope); the trailing `<|im_start|>assistant\n` is appended when
/// `add_generation_prompt` is set. An empty `messages` slice renders only
/// the generation prompt, matching Jinja's undefined-lookup semantics for
/// `messages[0]`.
pub(crate) fn render_chatml(messages: &[ChatMessage], add_generation_prompt: bool) -> String {
    let content_len: usize = messages.iter().map(|m| m.content.len()).sum();
    // Per-turn markers cost at most ~34 bytes ("<|im_start|>assistant\n" +
    // "<|im_end|>\n"); one more for the generation prompt.
    let mut out = String::with_capacity(content_len + 34 * (messages.len() + 1));

    if let Some(first) = messages.first() {
        if first.role == Role::System {
            push_turn(&mut out, Role::System, &first.content);
        }
    }
    for (index, message) in messages.iter().enumerate() {
        if index == 0 && message.role == Role::System {
            // Already emitted by the preamble; the template's loop skips it
            // via `message.role == "system" and not loop.first`.
            continue;
        }
        push_turn(&mut out, message.role, &message.content);
    }
    if add_generation_prompt {
        out.push_str(IM_START);
        out.push_str(Role::Assistant.as_str());
        out.push('\n');
    }
    out
}

/// Append one `<|im_start|>{role}\n{content}<|im_end|>\n` turn.
fn push_turn(out: &mut String, role: Role, content: &str) {
    out.push_str(IM_START);
    out.push_str(role.as_str());
    out.push('\n');
    out.push_str(content);
    out.push_str(IM_END);
    out.push('\n');
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn role_round_trips_through_str() {
        for role in [Role::System, Role::User, Role::Assistant] {
            assert_eq!(role.as_str().parse::<Role>().unwrap(), role);
        }
    }

    #[test]
    fn unknown_role_is_a_typed_error() {
        assert!(matches!(
            "tool".parse::<Role>().unwrap_err(),
            TokenizerError::UnsupportedRole(r) if r == "tool"
        ));
        assert!(matches!(
            "System".parse::<Role>().unwrap_err(),
            TokenizerError::UnsupportedRole(_)
        ));
    }

    #[test]
    fn message_json_rejects_unknown_roles_and_fields() {
        assert!(serde_json::from_str::<ChatMessage>(r#"{"role":"tool","content":"x"}"#).is_err());
        assert!(
            serde_json::from_str::<ChatMessage>(
                r#"{"role":"assistant","content":"","tool_calls":[]}"#
            )
            .is_err()
        );
        let ok: ChatMessage = serde_json::from_str(r#"{"role":"user","content":"hi"}"#).unwrap();
        assert_eq!(ok, ChatMessage::user("hi"));
    }

    #[test]
    fn empty_conversation_renders_only_the_generation_prompt() {
        assert_eq!(render_chatml(&[], true), "<|im_start|>assistant\n");
        assert_eq!(render_chatml(&[], false), "");
    }

    #[test]
    fn leading_system_is_rendered_once() {
        let rendered = render_chatml(&[ChatMessage::system("sys"), ChatMessage::user("hi")], true);
        assert_eq!(
            rendered,
            "<|im_start|>system\nsys<|im_end|>\n\
             <|im_start|>user\nhi<|im_end|>\n\
             <|im_start|>assistant\n"
        );
    }
}
