//! Tokenizer and chat-template rendering for installed `.rvmp` models.
//!
//! An install carries the upstream tokenizer verbatim under `tokenizer/`:
//!
//! ```text
//! model.rvmp/
//!   tokenizer/
//!     tokenizer.json           # HF fast-tokenizer definition (~11 MiB)
//!     tokenizer_config.json    # chat template + BOS policy
//!     generation_config.json   # stop tokens + sampling defaults
//! ```
//!
//! [`RvmpTokenizer::load`] reads all three with bounded, offline reads (no
//! network, files capped at [`MAX_TOKENIZER_FILE_BYTES`]) and validates
//! them against the verified architecture facts from
//! `docs/architecture.md`: stop tokens are exactly `{151645 <|im_end|>,
//! 151643 <|endoftext|>}`, the ChatML marker tokens map to their pinned
//! single ids, and BOS is never prepended.
//!
//! Chat rendering does **not** execute the checkpoint's Jinja template; the
//! 2507-Instruct template is vendored as Rust in [`chat`] and
//! snapshot-tested against reference `transformers` renders
//! (`fixtures/chat_fixtures.json`, regenerated by
//! `scripts/gen_tokenizer_fixtures.py`). The Jinja source is still stored
//! ([`RvmpTokenizer::chat_template`]) for provenance.

mod chat;
mod config;
mod error;

use std::fmt;
use std::fs;
use std::io::Read;
use std::path::Path;

use tokenizers::Tokenizer;

pub use chat::{ChatMessage, Role};
pub use error::TokenizerError;

use config::{GenerationConfigFile, TokenizerConfigFile};

/// Install-relative path of the tokenizer definition.
pub const TOKENIZER_FILE: &str = "tokenizer/tokenizer.json";

/// Install-relative path of the tokenizer config (chat template).
pub const TOKENIZER_CONFIG_FILE: &str = "tokenizer/tokenizer_config.json";

/// Install-relative path of the generation defaults.
pub const GENERATION_CONFIG_FILE: &str = "tokenizer/generation_config.json";

/// Read cap for any single tokenizer file. `tokenizer.json` is ~11 MiB;
/// the cap keeps a hostile install from driving an unbounded allocation.
pub const MAX_TOKENIZER_FILE_BYTES: u64 = 64 * 1024 * 1024;

/// `<|im_start|>` id in the pinned vocabulary.
pub const IM_START_TOKEN_ID: u32 = 151_644;

/// `<|im_end|>` id: the primary stop token (verified architecture fact).
pub const IM_END_TOKEN_ID: u32 = 151_645;

/// `<|endoftext|>` id: the secondary stop token (verified architecture
/// fact).
pub const ENDOFTEXT_TOKEN_ID: u32 = 151_643;

/// Sampling defaults from the checkpoint's `generation_config.json`.
///
/// For the pinned Qwen3-30B-A3B-Instruct-2507: temperature 0.7, top-p 0.8,
/// top-k 20. Fields the file omits fall back to the `transformers`
/// no-op defaults (temperature 1.0, top-p 1.0, no top-k).
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct SamplingDefaults {
    /// Softmax temperature.
    pub temperature: f32,
    /// Nucleus-sampling probability mass.
    pub top_p: f32,
    /// Top-k cutoff; `None` disables top-k truncation.
    pub top_k: Option<u32>,
}

/// The tokenizer of an installed model: encode/decode plus the vendored
/// chat template, stop tokens, and sampling defaults.
///
/// Loaded once at startup from the install directory; all operations after
/// [`load`](Self::load) are offline and read-only.
pub struct RvmpTokenizer {
    tokenizer: Tokenizer,
    chat_template: String,
    stop_tokens: Vec<u32>,
    sampling: SamplingDefaults,
}

impl fmt::Debug for RvmpTokenizer {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("RvmpTokenizer")
            .field("vocab_size", &self.tokenizer.get_vocab_size(true))
            .field("stop_tokens", &self.stop_tokens)
            .field("sampling", &self.sampling)
            .finish_non_exhaustive()
    }
}

impl RvmpTokenizer {
    /// Load and validate the tokenizer of the install at `rvmp_dir`.
    ///
    /// Reads `tokenizer/tokenizer.json`, `tokenizer/tokenizer_config.json`,
    /// and `tokenizer/generation_config.json` (bounded reads, no network)
    /// and cross-checks them against the pinned architecture facts. Fails
    /// with a typed [`TokenizerError`] on missing files, oversized files,
    /// malformed JSON, a missing chat template, a BOS-prepending config, or
    /// stop-token / special-token ids that contradict the pin.
    pub fn load(rvmp_dir: &Path) -> Result<Self, TokenizerError> {
        let tokenizer_path = rvmp_dir.join(TOKENIZER_FILE);
        let bytes = read_bytes_bounded(&tokenizer_path)?;
        let tokenizer = Tokenizer::from_bytes(&bytes).map_err(|e| TokenizerError::Backend {
            path: tokenizer_path.clone(),
            message: e.to_string(),
        })?;
        drop(bytes);

        let tokenizer_config: TokenizerConfigFile =
            read_json_bounded(&rvmp_dir.join(TOKENIZER_CONFIG_FILE))?;
        if tokenizer_config.add_bos_token == Some(true) {
            return Err(TokenizerError::BosNotAllowed);
        }
        let chat_template = tokenizer_config
            .chat_template
            .ok_or(TokenizerError::MissingChatTemplate)?;

        let generation_config: GenerationConfigFile =
            read_json_bounded(&rvmp_dir.join(GENERATION_CONFIG_FILE))?;
        let stop_tokens = generation_config.eos_token_id.into_vec();
        validate_stop_set(&stop_tokens)?;
        for (token, expected) in [
            (chat::IM_START, IM_START_TOKEN_ID),
            (chat::IM_END, IM_END_TOKEN_ID),
            ("<|endoftext|>", ENDOFTEXT_TOKEN_ID),
        ] {
            let found = tokenizer.token_to_id(token);
            if found != Some(expected) {
                return Err(TokenizerError::SpecialTokenMismatch {
                    token,
                    found,
                    expected,
                });
            }
        }

        let sampling = SamplingDefaults {
            temperature: generation_config.temperature.unwrap_or(1.0),
            top_p: generation_config.top_p.unwrap_or(1.0),
            top_k: generation_config.top_k,
        };

        tracing::debug!(
            dir = %rvmp_dir.display(),
            vocab_size = tokenizer.get_vocab_size(true),
            stop_tokens = ?stop_tokens,
            "loaded tokenizer"
        );

        Ok(RvmpTokenizer {
            tokenizer,
            chat_template,
            stop_tokens,
            sampling,
        })
    }

    /// Encode plain text to token ids.
    ///
    /// No BOS/EOS is added (this model never prepends BOS). Special-token
    /// text occurring inside `text` (e.g. a literal `<|im_end|>`) encodes
    /// to its single added-token id, matching the reference tokenizer's
    /// non-split behavior.
    pub fn encode(&self, text: &str) -> Result<Vec<u32>, TokenizerError> {
        let encoding = self
            .tokenizer
            .encode(text, false)
            .map_err(|e| TokenizerError::Encode(e.to_string()))?;
        Ok(encoding.get_ids().to_vec())
    }

    /// Decode token ids back to text.
    ///
    /// With `skip_special_tokens` unset, decoding is the exact inverse of
    /// [`encode`](Self::encode) (byte-level BPE is lossless, marker tokens
    /// reappear verbatim). With it set, special tokens such as
    /// `<|im_start|>` and `<|im_end|>` are dropped from the output.
    pub fn decode(&self, ids: &[u32], skip_special_tokens: bool) -> Result<String, TokenizerError> {
        self.tokenizer
            .decode(ids, skip_special_tokens)
            .map_err(|e| TokenizerError::Decode(e.to_string()))
    }

    /// Render a conversation to the prompt string, using the vendored
    /// 2507-Instruct ChatML template (see [`chat`] for fidelity notes).
    ///
    /// With `add_generation_prompt`, the string ends with
    /// `<|im_start|>assistant\n` so the model's reply begins immediately.
    pub fn render_chat(&self, messages: &[ChatMessage], add_generation_prompt: bool) -> String {
        chat::render_chatml(messages, add_generation_prompt)
    }

    /// Render a conversation and encode it: the token-id prompt for the
    /// forward pass.
    ///
    /// Token-for-token identical to the reference
    /// `apply_chat_template(..., tokenize=True)` (snapshot-tested): ChatML
    /// markers encode to their single special-token ids.
    pub fn encode_chat(
        &self,
        messages: &[ChatMessage],
        add_generation_prompt: bool,
    ) -> Result<Vec<u32>, TokenizerError> {
        self.encode(&self.render_chat(messages, add_generation_prompt))
    }

    /// Stop token ids, in `generation_config.json` order: `[151645
    /// <|im_end|>, 151643 <|endoftext|>]` for the pinned model. Generation
    /// stops when the model emits any of them.
    pub fn stop_tokens(&self) -> &[u32] {
        &self.stop_tokens
    }

    /// Sampling defaults from `generation_config.json`.
    pub fn sampling_defaults(&self) -> SamplingDefaults {
        self.sampling
    }

    /// The checkpoint's Jinja chat template, verbatim.
    ///
    /// Stored for provenance and inspection only — rendering uses the
    /// vendored Rust implementation, never this string.
    pub fn chat_template(&self) -> &str {
        &self.chat_template
    }
}

/// Validate that the configured stop tokens are exactly the pinned set
/// `{151645, 151643}` (order and duplicates ignored).
fn validate_stop_set(stop_tokens: &[u32]) -> Result<(), TokenizerError> {
    let mut set = stop_tokens.to_vec();
    set.sort_unstable();
    set.dedup();
    if set != [ENDOFTEXT_TOKEN_ID, IM_END_TOKEN_ID] {
        return Err(TokenizerError::EosMismatch {
            found: stop_tokens.to_vec(),
            expected: [IM_END_TOKEN_ID, ENDOFTEXT_TOKEN_ID],
        });
    }
    Ok(())
}

/// Read a whole file with a hard size cap.
fn read_bytes_bounded(path: &Path) -> Result<Vec<u8>, TokenizerError> {
    let file = fs::File::open(path).map_err(|e| TokenizerError::io(path, e))?;
    let too_large = || TokenizerError::FileTooLarge {
        path: path.to_path_buf(),
        max: MAX_TOKENIZER_FILE_BYTES,
    };
    // Fast fail on the reported size; the capped read below still governs
    // in case the metadata lies (procfs-style files).
    let metadata = file.metadata().map_err(|e| TokenizerError::io(path, e))?;
    if metadata.len() > MAX_TOKENIZER_FILE_BYTES {
        return Err(too_large());
    }
    let mut data = Vec::new();
    file.take(MAX_TOKENIZER_FILE_BYTES + 1)
        .read_to_end(&mut data)
        .map_err(|e| TokenizerError::io(path, e))?;
    if data.len() as u64 > MAX_TOKENIZER_FILE_BYTES {
        return Err(too_large());
    }
    Ok(data)
}

/// Read a JSON file with a hard size cap, then parse it.
fn read_json_bounded<T: serde::de::DeserializeOwned>(path: &Path) -> Result<T, TokenizerError> {
    let data = read_bytes_bounded(path)?;
    serde_json::from_slice(&data).map_err(|source| TokenizerError::Json {
        path: path.to_path_buf(),
        source,
    })
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::path::{Path, PathBuf};

    use serde::Deserialize;

    use super::*;
    use crate::format::testutil::TempDir;

    /// Committed fixtures: the pinned tokenizer files plus reference
    /// renders/encodings generated by `scripts/gen_tokenizer_fixtures.py`.
    fn fixtures_dir() -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR")).join("src/tokenizer/fixtures")
    }

    fn load_fixture_tokenizer() -> RvmpTokenizer {
        RvmpTokenizer::load(&fixtures_dir()).expect("fixture tokenizer loads")
    }

    #[derive(Deserialize)]
    struct FixtureFile {
        chat_cases: Vec<ChatCase>,
        text_cases: Vec<TextCase>,
    }

    #[derive(Deserialize)]
    struct ChatCase {
        name: String,
        messages: Vec<ChatMessage>,
        add_generation_prompt: bool,
        rendered: String,
        token_ids: Vec<u32>,
    }

    #[derive(Deserialize)]
    struct TextCase {
        text: String,
        token_ids: Vec<u32>,
    }

    fn load_fixtures() -> FixtureFile {
        let path = fixtures_dir().join("chat_fixtures.json");
        let data = fs::read_to_string(&path).expect("read chat_fixtures.json");
        serde_json::from_str(&data).expect("parse chat_fixtures.json")
    }

    /// A minimal install dir whose tokenizer files are copies of the
    /// fixtures, for corruption tests.
    fn copy_fixture_install(tmp: &TempDir) -> PathBuf {
        let dir = tmp.path().join("model.rvmp");
        fs::create_dir_all(dir.join("tokenizer")).unwrap();
        for file in [
            TOKENIZER_FILE,
            TOKENIZER_CONFIG_FILE,
            GENERATION_CONFIG_FILE,
        ] {
            fs::copy(fixtures_dir().join(file), dir.join(file)).unwrap();
        }
        dir
    }

    #[test]
    fn render_chat_matches_reference() {
        let tokenizer = load_fixture_tokenizer();
        for case in load_fixtures().chat_cases {
            let rendered = tokenizer.render_chat(&case.messages, case.add_generation_prompt);
            assert_eq!(rendered, case.rendered, "case {}", case.name);
        }
    }

    #[test]
    fn encode_chat_matches_reference() {
        let tokenizer = load_fixture_tokenizer();
        for case in load_fixtures().chat_cases {
            let ids = tokenizer
                .encode_chat(&case.messages, case.add_generation_prompt)
                .expect("encode_chat");
            assert_eq!(ids, case.token_ids, "case {}", case.name);
        }
    }

    #[test]
    fn plain_encode_matches_reference() {
        let tokenizer = load_fixture_tokenizer();
        for case in load_fixtures().text_cases {
            let ids = tokenizer.encode(&case.text).expect("encode");
            assert_eq!(ids, case.token_ids, "text {:?}", case.text);
        }
    }

    #[test]
    fn decode_round_trips_exactly() {
        let tokenizer = load_fixture_tokenizer();
        let fixtures = load_fixtures();
        for case in &fixtures.text_cases {
            let decoded = tokenizer.decode(&case.token_ids, false).expect("decode");
            assert_eq!(decoded, case.text);
        }
        for case in &fixtures.chat_cases {
            let decoded = tokenizer.decode(&case.token_ids, false).expect("decode");
            assert_eq!(decoded, case.rendered, "case {}", case.name);
        }
    }

    #[test]
    fn decode_can_skip_special_tokens() {
        let tokenizer = load_fixture_tokenizer();
        let ids = tokenizer
            .encode_chat(&[ChatMessage::user("hello there")], true)
            .unwrap();
        let stripped = tokenizer.decode(&ids, true).unwrap();
        assert!(!stripped.contains("<|im_start|>"));
        assert!(!stripped.contains("<|im_end|>"));
        assert!(stripped.contains("hello there"));
    }

    #[test]
    fn stop_tokens_match_the_pin() {
        let tokenizer = load_fixture_tokenizer();
        assert_eq!(
            tokenizer.stop_tokens(),
            [IM_END_TOKEN_ID, ENDOFTEXT_TOKEN_ID]
        );
    }

    #[test]
    fn sampling_defaults_come_from_generation_config() {
        let tokenizer = load_fixture_tokenizer();
        assert_eq!(
            tokenizer.sampling_defaults(),
            SamplingDefaults {
                temperature: 0.7,
                top_p: 0.8,
                top_k: Some(20),
            }
        );
    }

    #[test]
    fn chat_template_is_stored_verbatim() {
        let tokenizer = load_fixture_tokenizer();
        // The 2507-Instruct template starts with the tools branch; storing
        // it is provenance only, rendering never executes it.
        assert!(tokenizer.chat_template().starts_with("{%- if tools %}"));
        assert!(tokenizer.chat_template().contains("<|im_start|>"));
    }

    #[test]
    fn load_missing_install_is_a_typed_error() {
        let tmp = TempDir::new("tokenizer-missing");
        assert!(matches!(
            RvmpTokenizer::load(tmp.path()).unwrap_err(),
            TokenizerError::Io { .. }
        ));
    }

    #[test]
    fn load_rejects_garbage_tokenizer_json() {
        let tmp = TempDir::new("tokenizer-garbage");
        let dir = copy_fixture_install(&tmp);
        fs::write(dir.join(TOKENIZER_FILE), b"not a tokenizer").unwrap();
        assert!(matches!(
            RvmpTokenizer::load(&dir).unwrap_err(),
            TokenizerError::Backend { .. }
        ));
    }

    #[test]
    fn load_rejects_oversized_files() {
        let tmp = TempDir::new("tokenizer-oversize");
        let dir = copy_fixture_install(&tmp);
        // Sparse file over the cap; the metadata fast path rejects it
        // without reading.
        let file = fs::File::create(dir.join(TOKENIZER_FILE)).unwrap();
        file.set_len(MAX_TOKENIZER_FILE_BYTES + 1).unwrap();
        assert!(matches!(
            RvmpTokenizer::load(&dir).unwrap_err(),
            TokenizerError::FileTooLarge { .. }
        ));
    }

    #[test]
    fn load_rejects_wrong_stop_tokens() {
        let tmp = TempDir::new("tokenizer-eos");
        let dir = copy_fixture_install(&tmp);
        fs::write(
            dir.join(GENERATION_CONFIG_FILE),
            br#"{"eos_token_id": [1, 2], "temperature": 0.7}"#,
        )
        .unwrap();
        assert!(matches!(
            RvmpTokenizer::load(&dir).unwrap_err(),
            TokenizerError::EosMismatch { .. }
        ));
    }

    #[test]
    fn load_rejects_missing_chat_template_and_bos() {
        let tmp = TempDir::new("tokenizer-config");
        let dir = copy_fixture_install(&tmp);

        fs::write(dir.join(TOKENIZER_CONFIG_FILE), b"{}").unwrap();
        assert!(matches!(
            RvmpTokenizer::load(&dir).unwrap_err(),
            TokenizerError::MissingChatTemplate
        ));

        fs::write(
            dir.join(TOKENIZER_CONFIG_FILE),
            br#"{"chat_template": "x", "add_bos_token": true}"#,
        )
        .unwrap();
        assert!(matches!(
            RvmpTokenizer::load(&dir).unwrap_err(),
            TokenizerError::BosNotAllowed
        ));
    }
}
